apiVersion: v1
kind: Service
metadata:
  name: app-backend-clusterip-service
  labels:
    app: app-backend
spec:
  type: LoadBalancer
  selector:
    app: app-backend
  ports:
    - port: 5000
      targetPort: 5000