name: Build and push Docker images
on:
  push:
    tags:
    - '*'

env:
  IMAGE: azure-sample
  REGISTRY: ${{ secrets.DOCKER_ID }}

steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2.2.2
      with:
        push: true
        tags: $REGISTRY/$IMAGE:${GITHUB_REF/refs\/tags\//}