name: Release Version

on:
  push:
    branches:
      - master

env:
  IMAGE: azure-sample
  REGISTRY: ${{ secrets.DOCKER_ID }}

jobs:
  release-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@master
      id: bump-version
      with:
        github-token: ${{ secrets.GITHUB_TOKEN_ACTION }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: ''
        output-file: 'CHANGELOG.md'

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2.2.2
      with:
        push: true
        tags: $REGISTRY/$IMAGE:${{ steps.bump-version.outputs.version }}